trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - src/CSharpCodingStandards/TGC.CSharpCodingStandards/*
      - src/CSharpCodingStandards/Readme.md
      - src/CSharpCodingStandards/azure-pipelines.yml
      - src/CSharpCodingStandards/variables.yml

variables:
- template: 'variables.yml'
- name: csproj
  value: '**/TGC.CSharpCodingStandards.csproj'
- name: csprojTests
  value: '**/TGC.CSharpCodingStandards.Tests.csproj'
- name: BuildConfiguration
  value: 'release'
      
stages:
  - stage: build
    jobs:
      - job: build
        displayName: Build and save as artifact

        pool:
          name: Azure Pipelines
          vmImage: ubuntu-latest

        steps:
        - checkout: self 

        - task: NuGetToolInstaller@1
          displayName: 'Install NuGet'

        - task: PowerShell@2
          displayName: 'Set Assembly Version'
          inputs:
            filePath: 'src/CSharpCodingStandards/SetAssemblyVersion.ps1'
            arguments: >
              -AssemblyVersion "${{ variables.Major }}.${{ variables.Minor }}.${{ variables.Patch }}" 
              -RootPath "src/CSharpCodingStandards/"
        
        - task: DotNetCoreCLI@2
          displayName: Restore
          inputs:
            command: 'restore'
            projects: $(csproj)
            feedsToUse: 'select'

        - task: DotNetCoreCLI@2
          displayName: Build
          inputs:
            projects: $(csproj)
            arguments: '--configuration $(BuildConfiguration)'

        - task: DotNetCoreCLI@2
          displayName: Test
          inputs:
            command: test
            projects: $(csprojTests)
            arguments: '--configuration $(BuildConfiguration)'

        - task: DotNetCoreCLI@2
          displayName: "Pack"
          inputs:
            command: pack
            packagesToPack: $(csproj)
            majorVersion: ${{ variables.Major }}
            minorVersion: ${{ variables.Minor }}
            patchVersion: ${{ variables.Patch }}
            nbuild: true
            arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifact'
          inputs:
            targetPath: '$(Build.artifactstagingdirectory)/*.nupkg'
            ArtifactName: 'TGC.CSharpCodingStandards'
          condition: succeededOrFailed()

  - stage: Publish
    jobs:
      - job: PublishPackage
        displayName: Publish to feed
        condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
        pool:
          vmImage: ubuntu-latest
        steps:
        - download: current
          artifact: 'TGC.CSharpCodingStandards'
        - task: NuGetCommand@2
          inputs:
            command: push
            nuGetFeedType: 'internal'
            publishVstsFeed: 'Platform'
            packagesToPush: '$(Pipeline.Workspace)/**/*.nupkg'
            allowPackageConflicts: false