name: Nightly build

on:
  schedule:
  - cron: '0 5 * * *'
  # configure manual trigger
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
    - '.github/workflows/NightlyBuild.yml'
    - 'src/**'
  pull_request:
    branches: ["main"]
    paths:
    - '.github/workflows/NightlyBuild.yml'

jobs:
  project_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        csprojects: [AzureTableStorage, CSharpCodingStandards, EFCoreRepositories, HealthChecks, WebApiBuilder, Configuration, ConsoleBuilder]
    steps:
    # We need this because GitHub needs to clone the branch to pipeline
    - uses: actions/checkout@v3
    - name: Setup .NET Core SDK 6.0.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore src/${{ matrix.csprojects }}/TGC.${{ matrix.csprojects }}/TGC.${{ matrix.csprojects }}.csproj

    - name: Build
      run: dotnet build src/${{ matrix.csprojects }}/TGC.${{ matrix.csprojects }}/TGC.${{ matrix.csprojects }}.csproj --no-restore

    - name: Test
      run: dotnet test src/${{ matrix.csprojects }}/TGC.${{ matrix.csprojects }}.Tests/TGC.${{ matrix.csprojects }}.Tests.csproj

    - name: Pack
      run: dotnet pack src/${{ matrix.csprojects }}/TGC.${{ matrix.csprojects }}/TGC.${{ matrix.csprojects }}.csproj
