name: Nightly build

on:
  schedule:
  - cron: '0 5 * * *'
  # configure manual trigger
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # We need this because GitHub needs to clone the branch to pipeline
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x    

    - name: Restore dependencies
      run: dotnet restore **/*.csproj

    - name: Build
      run: dotnet build **/*.csproj --no-restore

    - name: Test
      run: dotnet test **/*Tests.csproj --no-restore

    - name: Pack
      run: dotnet pack **/*.csproj
