# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["main"]
    paths:
    - '.github/workflows/**'
    - '.github/CODEOWNERS'
    - 'src/CSharpCodingStandards'
  pull_request:
    branches: ["main"]
    paths:
    - '.github/workflows/**'
    - '.github/CODEOWNERS'
    - 'src/CSharpCodingStandards'


jobs:
  build_job:
    runs-on: ubuntu-latest
    env:
      projectName: TGC.CSharpCodingStandards

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore 'src/CSharpCodingStandards/$projectName/$projectName.csproj'
    - name: Build
      run: dotnet build 'src/CSharpCodingStandards/$projectName/$projectName.csproj' --no-restore
