# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build TGC.CodingStandards

on:
  push:
    branches: ["main"]
    paths:
    - '.github/workflows/**'
    - '.github/CODEOWNERS'
    - 'src/CSharpCodingStandards'
  pull_request:
    branches: ["main"]
    paths:
    - '.github/workflows/**'
    - '.github/CODEOWNERS'
    - 'src/CSharpCodingStandards'

jobs:
  build_job:
    runs-on: ubuntu-latest
    env:
      folder_name: CSharpCodingStandards
      project_name: TGC.CSharpCodingStandards
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src/$folder_name/$project_name/$project_name.csproj
    - name: Build
      run: dotnet build src/$folder_name/$project_name/$project_name.csproj --no-restore
