name: Build TGC.AzureTableStorage

on:
  push:
    branches: ["main"]
    paths:
    - '.github/workflows/TGC.AzureTableStorage.yml'
    - 'src/AzureTableStorage/**'
  pull_request:
    branches: ["main"]
    paths:
    - '.github/workflows/TGC.AzureTableStorage.yml'
    - 'src/AzureTableStorage/**'

jobs:
  build_job:
    runs-on: ubuntu-latest
    env:
      folder_name: AzureTableStorage
      project_name: TGC.AzureTableStorage
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src/$folder_name/$project_name/$project_name.csproj
    - name: Build
      run: dotnet build src/$folder_name/$project_name/$project_name.csproj --no-restore
